import Link from "next/link";
import { fromZonedTime } from "date-fns-tz";
import { Card } from "@/components/ui/card";
import { getAdminContextOrRedirect } from "@/lib/admin/auth";
import { createServerSupabase } from "@/lib/supabase/server";
import { formatPoints } from "@/lib/utils";
import { getHomeBannerNotifications } from "@/lib/notifications/queries";
import { HomeBanners } from "./HomeBanners";

/**
 * /admin — today's overview.
 *
 * Three stat cards: today's bookings, unread chat (across all threads),
 * Inner Circle members. Below: a list of today's bookings ordered by
 * start time, each row clicks through to /admin/bookings#<id>.
 */
export default async function AdminTodayPage() {
  const ctx = await getAdminContextOrRedirect();
  const supabase = await createServerSupabase();

  const tz = "Europe/London";
  const now = new Date();
  const ymd = now.toLocaleDateString("en-CA", { timeZone: tz });
  const dayStart = fromZonedTime(`${ymd}T00:00:00`, tz);
  const dayEnd = fromZonedTime(`${ymd}T23:59:59.999`, tz);

  const [todayBookingsResult, unreadResult, innerCircleResult] = await Promise.all([
    supabase
      .from("bookings")
      .select(
        "id, starts_at, status, services (name), staff!bookings_staff_id_fkey (display_name), clients (full_name, email)"
      )
      .eq("tenant_id", ctx.tenantId)
      .gte("starts_at", dayStart.toISOString())
      .lt("starts_at", dayEnd.toISOString())
      .order("starts_at", { ascending: true }),
    supabase
      .from("chat_threads")
      .select("unread_count_staff")
      .eq("tenant_id", ctx.tenantId)
      .gt("unread_count_staff", 0),
    supabase
      .from("loyalty_accounts")
      .select("id", { count: "exact", head: true })
      .eq("tenant_id", ctx.tenantId)
      .eq("tier", "inner_circle"),
  ]);

  const todayBookings = (todayBookingsResult.data ?? []) as Array<{
    id: string;
    starts_at: string;
    status: string;
    services: unknown;
    staff: unknown;
    clients: unknown;
  }>;
  const unreadCount = (unreadResult.data ?? []).reduce(
    (acc, row) => acc + ((row.unread_count_staff as number | null) ?? 0),
    0
  );
  const innerCircleCount = innerCircleResult.count ?? 0;

  const greeting = getGreeting();
  const banners = await getHomeBannerNotifications().catch(() => []);

  // Pending bank holiday decisions within 30 days surface as synthetic
  // home banners. The persisted reminder notifications are still
  // generated by the daily cron at the 2-month / 2-week marks.
  const horizonYmd = new Date(Date.now() + 30 * 86_400_000)
    .toISOString()
    .slice(0, 10);
  const todayYmd = new Date().toISOString().slice(0, 10);
  const { data: bhPending } = await supabase
    .from("bank_holiday_decisions")
    .select("id, date, name")
    .eq("tenant_id", ctx.tenantId)
    .eq("decision", "pending")
    .gte("date", todayYmd)
    .lte("date", horizonYmd)
    .order("date", { ascending: true })
    .limit(3);
  const bankHolidayBanners = ((bhPending ?? []) as Array<{
    id: string;
    date: string;
    name: string;
  }>).map((b) => {
    const days = Math.max(
      0,
      Math.ceil((new Date(`${b.date}T00:00:00`).getTime() - Date.now()) / 86_400_000)
    );
    return {
      id: `bh:${b.id}`,
      kind: "bank_holiday_reminder",
      title: `${b.name} is in ${days} day${days === 1 ? "" : "s"} — no decision yet`,
      body: "Decide now so the booking page reflects it.",
      actionUrl: "/admin/settings?tab=schedule",
      priority: days <= 14 ? "urgent" : "high",
    };
  });

  return (
    <div className="flex flex-col gap-6">
      <header className="flex items-baseline justify-between">
        <div>
          <h1 className="font-serif text-[28px] font-medium leading-tight tracking-tight text-olive">
            {greeting}, {ctx.staffName ?? "team"}.
          </h1>
          <p className="mt-1 text-[13px] tracking-snug text-olive-soft">
            {dayLabel(now, tz)}
          </p>
        </div>
      </header>

      {(banners.length > 0 || bankHolidayBanners.length > 0) && (
        <HomeBanners
          items={[
            ...banners.map((b) => ({
              id: b.id,
              kind: b.kind,
              title: b.title,
              body: b.body,
              actionUrl: b.actionUrl,
              priority: b.priority,
            })),
            ...bankHolidayBanners,
          ]}
        />
      )}

      <div className="grid gap-3 sm:grid-cols-3">
        <StatCard
          label="Today's bookings"
          value={String(todayBookings.length)}
          href="/admin/bookings"
        />
        <StatCard
          label="Unread messages"
          value={String(unreadCount)}
          href="/admin/inbox"
        />
        <StatCard
          label="Inner Circle members"
          value={formatPoints(innerCircleCount)}
          href="/admin/clients"
        />
      </div>

      <section>
        <h2 className="font-serif text-[22px] font-medium tracking-tight text-olive">
          Today&rsquo;s schedule
        </h2>
        {todayBookings.length === 0 ? (
          <Card className="mt-4 p-5">
            <p className="text-[13px] tracking-snug text-olive-soft">
              No bookings today. Catch your breath.
            </p>
          </Card>
        ) : (
          <ul className="mt-4 flex flex-col gap-2">
            {todayBookings.map((b) => (
              <BookingRow
                key={b.id}
                id={b.id}
                startsAt={b.starts_at}
                status={b.status}
                services={b.services}
                staff={b.staff}
                clients={b.clients}
              />
            ))}
          </ul>
        )}
      </section>
    </div>
  );
}

function StatCard({
  label,
  value,
  href,
}: {
  label: string;
  value: string;
  href: string;
}) {
  return (
    <Link href={href} className="block focus-visible:outline-none">
      <Card interactive className="p-5">
        <p className="text-[11px] font-medium uppercase tracking-label-caps text-olive-soft">
          {label}
        </p>
        <p className="mt-2 font-serif text-[32px] font-medium leading-none tracking-tightest tabular-nums text-olive">
          {value}
        </p>
      </Card>
    </Link>
  );
}

function BookingRow({
  id,
  startsAt,
  status,
  services,
  staff,
  clients,
}: {
  id: string;
  startsAt: string;
  status: string;
  services: unknown;
  staff: unknown;
  clients: unknown;
}) {
  const service = pickFirst<{ name: string }>(services);
  const staffRow = pickFirst<{ display_name: string }>(staff);
  const client = pickFirst<{ full_name: string | null; email: string | null }>(clients);
  const time = new Date(startsAt)
    .toLocaleTimeString("en-GB", {
      hour: "numeric",
      minute: "2-digit",
      hour12: true,
      timeZone: "Europe/London",
    })
    .replace(/\s+/g, "")
    .toLowerCase();

  return (
    <li>
      <Link
        href={`/admin/bookings?focus=${id}`}
        className="block focus-visible:outline-none"
      >
        <Card interactive className="flex items-center gap-4 p-4">
          <span className="w-16 flex-shrink-0 font-serif text-[18px] font-medium tabular-nums text-olive">
            {time}
          </span>
          <div className="flex-1">
            <p className="text-[14px] font-medium tracking-snug text-olive">
              {service?.name ?? "Session"}
            </p>
            <p className="mt-0.5 text-[12px] tracking-snug text-olive-soft">
              {client?.full_name ?? client?.email ?? "—"} · with {staffRow?.display_name ?? "staff"}
            </p>
          </div>
          <StatusPill status={status} />
        </Card>
      </Link>
    </li>
  );
}

function StatusPill({ status }: { status: string }) {
  const palette: Record<string, { bg: string; fg: string }> = {
    confirmed: { bg: "rgba(117,133,100,0.10)", fg: "#5C6B4E" },
    pending: { bg: "rgba(184,148,90,0.10)", fg: "#B8945A" },
    completed: { bg: "rgba(117,133,100,0.16)", fg: "#3E3E31" },
    cancelled: { bg: "rgba(212,91,91,0.10)", fg: "#D45B5B" },
    no_show: { bg: "rgba(212,91,91,0.10)", fg: "#D45B5B" },
  };
  const { bg, fg } = palette[status] ?? { bg: "rgba(62,62,49,0.06)", fg: "#3E3E31" };
  return (
    <span
      className="rounded-full px-2.5 py-1 text-[11px] font-medium uppercase tracking-label-caps"
      style={{ background: bg, color: fg }}
    >
      {status.replace("_", " ")}
    </span>
  );
}

function pickFirst<T>(value: unknown): T | null {
  if (value == null) return null;
  if (Array.isArray(value)) return (value[0] as T) ?? null;
  return value as T;
}

function dayLabel(d: Date, tz: string): string {
  return d.toLocaleDateString("en-GB", {
    weekday: "long",
    day: "numeric",
    month: "long",
    timeZone: tz,
  });
}

function getGreeting(): string {
  const h = new Date().getHours();
  if (h < 12) return "Good morning";
  if (h < 18) return "Good afternoon";
  return "Good evening";
}
